### ISSUE TITLE
Build cpp in another directory

### ISSUE THREAD

**Issue by root0x** [sonicdoe/grunt-node-gyp#4]
Hi, I have my gruntfile stored in the root of my project. The native node addons are stores in the cpp/ directory of the project, this means that node-gyp build does not work correctly.  How can you specify in the gruntfile to build the cpp source which is stored in another directory?

**Comment by sonicdoe** [comment]
Is your `binding.gyp` also in the `cpp` directory? Would `node-gyp build --directory=cpp` work for you?

**Comment by root0x** [comment]
Running node-gyp build --directory=cpp in the root of my project works perfectly, but when i try and integrate it with grunt it fails. My Gruntfile is 
```
gyp: {
  addon: {
        command: 'build',
        options: {
            directory : 'cpp'
        }
    }
},
```
And i'm getting the errors of
 ```
  Warning: `gyp` failed with exit code: 1 Use --force to continue.

    Aborted due to warnings.
Warning: gyp: binding.gyp not found (cwd: /Users/danieldoynov/Documents/puma/api-pumaportal) while trying to load binding.gyp Use --force to continue.
```
I just don't understand why its not searching in the cpp/ directory and is still just in the root of the project. Have you got any suggestions on how to fix this?

**Comment by root0x** [comment]
I solved this by just moving the binding.gyp to the root of the project, and just changing the sources line in the binding.gyp to point to the new relative path of the source files.

**Comment by sonicdoe** [comment]
Yes, that is certainly a good way to solve it 👍 `options: { directory: 'cpp' }` does not work because grunt-node-gyp currently doesn’t support the `--directory` option. I’m planning to add support for it in the future.
